### PR TITLE
Use jclse10_29 alt library for jlink image

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Jenkins test sanity plinux jdk10

**Comment by andrew-m-leonard** [comment]
Fixes #19

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by andrew-m-leonard** [comment]
jenkins line endings check

**Pull request merged**
