### PR TITLE
Export the CONFIG_SHELL variable

### PR DESCRIPTION
**Pull request by dnakamura**
This variable identifies which shell to use when running future instances
of configure

Issue eclipse/omr#2567

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
There should be a second generated-configure.sh file updated, even if its only a DATE_WHEN_GENERATED change.

Are you planning to change the other extension versions as well? i.e. 8, 9, head

**Comment by pshipton** [comment]
Is this the final part to resolve eclipse/omr#2567, at least for jdk10, or are there more changes coming?

**Comment by dnakamura** [comment]
This is it. PR open on head, will open one on 8.
Updating the other configure now

**Comment by pshipton** [comment]
Note we plan to do a final release build for Java 9, so Adopt might need the fix on 9 as well.

**Comment by pshipton** [comment]
jenkins compile plinux

**Pull request merged**
