### PR TITLE
Remove make/common/Modules.gmk MODULES_DEPS_MAKEFILE patch

### PR DESCRIPTION
**Pull request by ben-walsh**
Signed-off-by: Ben Walsh ben_walsh@uk.ibm.com

### CODE REVIEW

**Comment by ben-walsh** [comment]
Build : https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_ibmsdk/320

**Comment by ben-walsh** [comment]
Jenkins test sanity plinux jdk10

**Comment by pshipton** [comment]
Could we have some justification for why this patch is no longer needed please.

**Comment by andrew-m-leonard** [comment]
(from my memory!) We had to add this patch to correctly generate the module_deps dependency targets including the J9 modules. As we want to remove all make file patches, we wanted to see if the latest openjdk make file logic correctly achieves the same result, and from our testing it does :-)

**Comment by pshipton** [comment]
jenkins test sanity plinux

**Pull request merged**
